<div style="width: 100%; clear: both;">
<div style="float: left; width: 30%;">
<img src="https://www.utpl.edu.ec/sites/default/files/archivos/marca%20UTPL%202018-02.png", align="left" width="280" height="120">
</div>
</div>
<div style="float: right; width: 70%;">
<p style="margin: 0; padding-top: 32px; text-align:right; color:#003366; font-size:16px"><u>Análisis de datos y visualización</u></p>
<p style="margin: 0; text-align:right; color:#999999; font-size:17px">Maestría en Inteligencia Artificial Aplicada</p>
</div>
</div>
<div style="width: 100%; clear: both;">
<div style="width:100%;">&nbsp;</div>


# Predicción numérica mediante métodos de Machine learning

Source: https://github.com/jcarpenter12/Regression-Analysis-Using-Python/blob/master/notebook.ipynb

## Carga del dataset: Boston housing

El conjunto de datos contiene datos de precios de viviendas de Boston.

- Number of Instances: 506 

- Number of Attributes: 14 numeric (including y)

- Attribute Information (in order):
    - CRIM     per capita crime rate by town
    - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
    - INDUS    proportion of non-retail business acres per town
    - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
    - NOX      nitric oxides concentration (parts per 10 million)
    - RM       average number of rooms per dwelling
    - AGE      proportion of owner-occupied units built prior to 1940
    - DIS      weighted distances to five Boston employment centres
    - RAD      index of accessibility to radial highways
    - TAX      full-value property-tax rate per $10,000
      
    - PTRATIO  pupil-teacher ratio by town
    - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
    - LSTAT    % lower status of the population
    - MEDV     Median value of owner-occupied homes in $1000's -> variable a predecir.

:Missing Attribute Values: None

:Creator: Harrison, D. and Rubinfeld, D.L.

Se usará una copia del dataset housing, disponible en "UCI ML": http://archive.ics.uci.edu/ml/datasets/Housing

In [122]:
# Librerías a utilizar
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

# Métodos de regresión no lineal:

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

from sklearn import preprocessing # para el escalado

from sklearn.model_selection import GridSearchCV # para búsqueda de hiperparámetros

### Preparación de datasets (entrenamiento y test)
from sklearn.model_selection import train_test_split
import calendar

In [123]:
#Carga del dataset:

data_url = "online_shoppers_intention.csv"
data = pd.read_csv(data_url, sep=',', header=0)
column_names=data.columns
x_columns = column_names[0:data.shape[1]-1]
y_column = column_names[data.shape[1]-1]

#X = data[x_columns]   # variables predictoras
#y = data[y_column]    # variable a predecir
data[:10]

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
5,0,0.0,0,0.0,19,154.216667,0.015789,0.024561,0.0,0.0,Feb,2,2,1,3,Returning_Visitor,False,False
6,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.4,Feb,2,4,3,3,Returning_Visitor,False,False
7,1,0.0,0,0.0,0,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,2,1,5,Returning_Visitor,True,False
8,0,0.0,0,0.0,2,37.000000,0.000000,0.100000,0.0,0.8,Feb,2,2,2,3,Returning_Visitor,False,False
9,0,0.0,0,0.0,3,738.000000,0.000000,0.022222,0.0,0.4,Feb,2,4,1,2,Returning_Visitor,False,False

In [143]:
X

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True

In [124]:
data.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')

In [125]:
data.sample(10)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
11123,0,0.000000,0,0.0,23,1202.750000,0.000000,0.004545,0.000000,0.0,Dec,8,13,9,20,Other,True,False
11097,3,29.250000,0,0.0,32,1729.750000,0.000000,0.005714,16.729370,0.0,Dec,2,4,3,2,New_Visitor,False,True
402,5,197.000000,4,246.0,17,427.083333,0.000000,0.008696,0.000000,0.0,Mar,1,1,3,2,New_Visitor,False,False
7291,1,383.800000,0,0.0,11,92.400000,0.000000,0.016667,0.000000,0.0,Jul,2,2,9,2,New_Visitor,False,False
2247,10,295.694056,0,0.0,29,785.474359,0.000000,0.001481,34.991667,0.0,May,2,2,5,4,Returning_Visitor,True,True
944,11,267.166667,0,0.0,39,881.441667,0.004167,0.011458,20.117513,0.0,Mar,2,2,3,1,New_Visitor,False,False
5746,5,151.333333,0,0.0,11,283.333333,0.033333,0.058333,13.910470,0.0,Nov,2,2,6,20,Returning_Visitor,False,True
9814,4,53.750000,0,0.0,41,1130.807540,0.019048,0.018783,0.000000,0.0,Dec,3,2,1,2,Returning_Visitor,False,False
5310,0,0.000000,0,0.0,2,73.000000,0.000000,0.050000,0.000000,0.0,May,1,1,1,3,Returning_Visitor,False,False
10614,0,0.000000,0,0.0,7,202.250000,0.000000,0.028571,0.000000,0.0,Dec,1,1,2,2,Returning_Visitor,False,False

In [126]:
data.iloc[:, 0:10]

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0

In [127]:
len(data)

12330

In [128]:
data.shape

(12330, 18)

In [129]:
x_columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend'],
      dtype='object')

In [130]:
y_column

'Revenue'

In [131]:
def codificar_mes(mes):
    if mes=='June':
        mes='Jun'
    numero=list(calendar.month_abbr).index(mes)
    return numero
    
data['Month']=data['Month'].map(codificar_mes)
data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,2,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,2,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,2,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,12,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,11,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,11,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,11,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,11,3,2,1,2,New_Visitor,True,False

In [132]:
data['Month'].value_counts()

Month
5     3364
11    2998
3     1907
12    1727
10     549
9      448
8      433
7      432
6      288
2      184
Name: count, dtype: int64

In [133]:
def codificar_visitor_type(visitor):
    if visitor=='Returning_Visitor':
        visitor=1
    if visitor=='New_Visitor':
        visitor=2
    if visitor=='Other':
        visitor=3
    return visitor
data['VisitorType']=data['VisitorType'].map(codificar_visitor_type)
data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,1,1,1,1,1,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,2,2,2,1,2,1,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,4,1,9,3,1,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,2,3,2,2,4,1,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,2,3,3,1,4,1,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,12,4,6,1,1,1,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,11,3,2,1,8,1,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,11,3,2,1,13,1,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,11,2,2,3,11,1,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,11,3,2,1,2,2,True,False

In [134]:
data['VisitorType'].value_counts()

VisitorType
1    10551
2     1694
3       85
Name: count, dtype: int64

In [135]:
def codificar_en_binario(valor):
    if str(valor)=='False':
        valor=0
    else:
        valor=1
    return valor
data['Weekend']=data['Weekend'].map(codificar_en_binario)
data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,1,1,1,1,1,0,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,2,2,2,1,2,1,0,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,4,1,9,3,1,0,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,2,3,2,2,4,1,0,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,2,3,3,1,4,1,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,12,4,6,1,1,1,1,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,11,3,2,1,8,1,1,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,11,3,2,1,13,1,1,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,11,2,2,3,11,1,0,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,11,3,2,1,2,2,1,False

In [136]:
data['Weekend'].value_counts()

Weekend
0    9462
1    2868
Name: count, dtype: int64

In [137]:
data['Revenue']=data['Revenue'].map(codificar_en_binario)
data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,1,1,1,1,1,0,0
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,2,2,2,1,2,1,0,0
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,4,1,9,3,1,0,0
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,2,3,2,2,4,1,0,0
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,2,3,3,1,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,12,4,6,1,1,1,1,0
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,11,3,2,1,8,1,1,0
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,11,3,2,1,13,1,1,0
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,11,2,2,3,11,1,0,0
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,11,3,2,1,2,2,1,0

In [138]:
data['Revenue'].value_counts()

Revenue
0    10422
1     1908
Name: count, dtype: int64

In [139]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  int64
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  int64
 16  Weekend                  12330 non-null  int64
 17  Revenue                  12330 non-null  int64
dtypes: float64(7), int64(11)
memory usage: 1.7 MB

In [161]:
data.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,7.651987,2.124006,2.357097,3.147364,4.069586,1.151176,0.232603,0.154745
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,3.392841,0.911325,1.717277,2.401591,4.025169,0.376989,0.422509,0.361676
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,5.000000,2.000000,2.000000,1.000000,2.000000,1.000000,0.000000,0.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,7.000000,2.000000,2.000000,3.000000,2.000000,1.000000,0.000000,0.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,11.000000,3.000000,2.000000,4.000000,4.000000,1.000000,0.000000,0.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,12.000000,8.000000,13.000000,9.000000,20.000000,3.000000,1.000000,1.000000

In [144]:
X = data[x_columns]   # variables predictoras
y = data[y_column]    # variable a predecir

In [149]:
X

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,1,1,1,1,1,0
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,2,2,2,1,2,1,0
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,4,1,9,3,1,0
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,2,3,2,2,4,1,0
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,2,3,3,1,4,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,12,4,6,1,1,1,1
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,11,3,2,1,8,1,1
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,11,3,2,1,13,1,1
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,11,2,2,3,11,1,0
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,11,3,2,1,2,2,1

In [150]:
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
12325    0
12326    0
12327    0
12328    0
12329    0
Name: Revenue, Length: 12330, dtype: int64

### Creación de datasets para el training y testing

In [151]:

X_train, X_test,y_train, y_test = train_test_split(X, y,test_size=0.20,random_state=10, shuffle=True)

## 1. Decision Tree Learning

### 1.1 Parámetros clave de un árbol de decisión

- <b>max_depth</b> (None | int): es la profundidad máxima de un árbol.
    - Se utiliza para controlar el sobreajuste: a una mayor profundidad el modelo aprenderá relaciones muy específicas de del train dataset.
    - Si su su valor es <i>None</i>, los nodos se expanden hasta que todas las hojas sean puras o hasta que todas las hojas contengan menos de <i>min_samples_split</i> observaciones.
    - Requiere ajuste.


- <b>min_samples_split</b>: define el número mínimo de observaciones que se requieren en un nodo para ser considerado para la división.
    - Valores demasiado altos pueden provocar un ajuste insuficiente, es decir, impiden que un modelo aprenda relaciones que podrían ser muy específicas de una muestra particular.
    - Su valor se puede establecer en alrededor del 0,5-1% de las observaciones. 
    - Se utiliza para controlar el overfitting, por lo que este es un parámetro que generalmente requiere ajuste.

- <b>min_samples_leaf</b>: define las muestras (u observaciones) mínimas requeridas en un nodo terminal u hoja.
    - Se utiliza para controlar el sobreajuste similar a <i>min_samples_split</i>.
    - Para empezar, se puede establecer en alrededor del 1% de todas las observaciones en el conjunto de datos.
    - Un valor demasiado pequeño hace que el modelo sea más propenso a capturar ruido y, por lo tanto, a sobreajustarse.

- <b>max_features</b>: número máximo de características a considerar para buscar la mejor división.

    - En dataset de pocas características, podemos trabajar con el valor de 1.0, lo cual significa, considerar una variable para la búsqueda.
    - En conjuntos de datos grandes, como de 100 variables (m) se puede optar por tomar la raiz cuadrada de m (es decir, 10), o debemos verificar hasta el 30-40% del número total de características.
    - Los valores más altos pueden provocar un ajuste excesivo, pero depende de cada caso.
      
- <b>random_state</b>: La semilla de número aleatorio generada cada vez. Un número aleatorio fijo es importante ya que, de lo contrario, tendríamos resultados diferentes en cada ejecución posterior, especialmente importante en el proceso de ajuste.

- <b>max_leaf_nodes</b>: número máximo de nodos terminales u hojas en un árbol.
    - Se puede definir en lugar de max_depth.

### 1.2 Primer experimento: con todos los parámetros por defecto

In [152]:
#############
# Training
#############

dtr = DecisionTreeRegressor(random_state = 10) # Crear una instancia de DecisionTreeRegressor

dtr.fit(X_train, y_train) # crear el modelo a partir del dataset de entrenamiento

#############
# Predicción
predicted = dtr.predict(X_test) # generar predicción para el dataset de test
dtr_predictions = pd.DataFrame({'Actual':y_test,'Predicted':predicted}) # imprimir (y_real, y_predicted)
print(dtr_predictions[:5])
#############


#############
# Imprimir parámetros usados por el modelo
#############
print('Max features:', dtr.max_features_) # todas las variables fueron usadas para el split
print('Depth of the Decision Tree :', dtr.get_depth()) #  imprimir profundidad del árbol

       Actual  Predicted
10987       1        0.0
11878       1        0.0
11127       1        0.0
2486        0        0.0
392         0        0.0
Max features: 17
Depth of the Decision Tree : 26

In [153]:
#############
# Importancia de las variables al momento de crear el modelo:
#############

importances_sk = dtr.feature_importances_ # obtener coeficientes de variables

print(importances_sk) # imprimir coeficientes de variables

# Crear un dataframe con las variables y su importancia:
feature_importance_sk = {}
for i, feature in enumerate(x_columns):
    feature_importance_sk[feature] = round(importances_sk[i], 3)

print(f"Feature importance by sklearn: {feature_importance_sk}")

[0.05371782 0.0608457  0.01120609 0.01525086 0.05252125 0.07494236
 0.07803556 0.07151249 0.43964722 0.00200473 0.04724706 0.01252442
 0.01681806 0.02837021 0.0246132  0.00383826 0.00690471]
Feature importance by sklearn: {'Administrative': 0.054, 'Administrative_Duration': 0.061, 'Informational': 0.011, 'Informational_Duration': 0.015, 'ProductRelated': 0.053, 'ProductRelated_Duration': 0.075, 'BounceRates': 0.078, 'ExitRates': 0.072, 'PageValues': 0.44, 'SpecialDay': 0.002, 'Month': 0.047, 'OperatingSystems': 0.013, 'Browser': 0.017, 'Region': 0.028, 'TrafficType': 0.025, 'VisitorType': 0.004, 'Weekend': 0.007}

In [154]:
################################
# Evaluación
################################

# Train dataset:
accuracy_train = dtr.score(X_train, y_train)
print('accuracy_score on train dataset : ', accuracy_train)

# Test dataset:
score = dtr.score(X_test,y_test)
mseFull = np.mean((y_test - predicted)**2)

print("Accuracy of model: %f" % score)
print("Mean Squared Error: %f" % mseFull)

accuracy_score on train dataset :  1.0
Accuracy of model: -0.130370
Mean Squared Error: 0.146391

In [155]:
################################
### Imprimir el modelo
################################
from sklearn import tree
text_representation = tree.export_text(dtr, feature_names=x_columns) # exportar el modelo en texto
#print(text_representation) # descomentar para visualizar

In [156]:
# import export_graphviz 
from sklearn.tree import export_graphviz  
  
# exportar el árbol a un archivo tree.dot 
export_graphviz(dtr, out_file ='tree.png', 
               feature_names = x_columns)

### 1.3 Segundo experimento: usando como la parámetro la profundidad máxima

In [157]:
dtr = DecisionTreeRegressor(random_state = 10,
                            max_depth=13) # 

dtr.fit(X_train, y_train)

predicted = dtr.predict(X_test)

################################
# Evaluación
################################

# Train dataset
accuracy_train = dtr.score(X_train, y_train)
print('accuracy_score on train dataset : ', accuracy_train)

# Test dataset
score = dtr.score(X_test,y_test)
mseFull = np.mean((y_test - predicted)**2)

print("Accuracy of model: %f" % score)
print("Mean Squared Error: %f" % mseFull)

accuracy_score on train dataset :  0.839920036025563
Accuracy of model: 0.067852
Mean Squared Error: 0.120720

### 1.4 Tercer experimento: usando otros parámetros

In [158]:
dtr = DecisionTreeRegressor(random_state = 10,
                            max_depth=13, 
                            min_samples_split=4,
                           min_samples_leaf=4,
                           max_features=1.0)


dtr.fit(X_train, y_train)

predicted = dtr.predict(X_test)

print('Depth of the Decision Tree :', dtr.get_depth()) # depth of the decision tree


################################
# Evaluación
################################

# Train dataset

accuracy_train = dtr.score(X_train, y_train)
print('accuracy_score on train dataset : ', accuracy_train)

# Test dataset
score = dtr.score(X_test,y_test)
mseFull = np.mean((y_test - predicted)**2)

print("Accuracy of model: %f" % score)
print("Mean Squared Error: %f" % mseFull)

Depth of the Decision Tree : 13
accuracy_score on train dataset :  0.7334905837939205
Accuracy of model: 0.173069
Mean Squared Error: 0.107093

De lo anterior podemos ver que un árbol de decisión ha funcionado mejor que con los parámetros por defecto. 

Los árboles de decisión tienen varios hiperparámetros diferentes. Para intentar mejorar el modelo debemos hacer experimentos usando una  búsqueda en grids y validación cruzada.

### 1.5 Tuning mediante Grid Search & Cross Validation

- Grid Search se utiliza para ejecutar un modelo repetidamente cada vez con diferentes parámetros especificados por el usuario.

- Cross validation se utiliza para entrenar con subconjuntos de datos (chunks o folds), especificados por la opción "cv". El valor de cv principalmente depende del tamaño del conjunto de datos:
    - Si el tamaño es pequeño: un número razonable pueden ser 10 o más; un número como este puede ser beneficioso porque permite utilizar una mayor proporción de datos para entrenamiento en cada iteración.
    - Si el tamaño es grande: un número menor de folds como 5 suele ser suficiente y reduce el tiempo de computación.

In [159]:
dtr = DecisionTreeRegressor(random_state=10, 
                            max_features=1.0)

params = {'min_samples_split': range(2, 20, 2), #range(start, stop, step)
          'min_samples_leaf': range(2, 20, 2),
          'max_depth': range(5, 15)}
    
grid_search = GridSearchCV(dtr, param_grid=params, cv=10)
grid_search.fit(X_train, y_train) #training

# Obtener el mejor modelo
best_model = grid_search.best_estimator_

# Ver los mejores hiperparámetros encontrados
print("Mejores hiperparámetros: ", grid_search.best_params_)

Mejores hiperparámetros:  {'max_depth': 5, 'min_samples_leaf': 18, 'min_samples_split': 2}

In [160]:
# Generar predicciones en el conjunto de prueba
y_test_pred = best_model.predict(X_test)

# Evaluar el rendimiento del mejor modelo:
mse = mean_squared_error(y_test, y_test_pred)
print(f"Mean Squared Error en el conjunto de prueba: {mse}")

score = best_model.score(X_test, y_test) 
print("R^2 del mejor modelo: %f" % score)

Mean Squared Error en el conjunto de prueba: 0.07807397174887569
R^2 del mejor modelo: 0.397145

## Random Forest Model

Un bosque aleatorio, como su nombre indica, es una colección de árboles de decisión. 

Esto es particularmente útil ya que los árboles de decisión son propensos al sobreajuste (el sobreajuste. Un bosque aleatorio reduce esto en ejecutar cada árbol de decisión en un subconjunto diferente de datos y luego hace una predicción basada en la suma de las predicciones de todos los árboles del bosque.

#### Random Forest Parameters

Como un bosque aleatorio es una colección de árboles de decisión, los parámetros son en gran medida los mismos. He anotado los principales parámetros forestales específicos a continuación.

 - <b>n_estimators</b>: La cantidad de árboles a utilizar para construir el modelo predictivo antes de tomar el promedio de ellos. Generalmente, cuanto más alto, mejor, pero también consume más CPU.
   
 - <b>oob_score</b>: Esta es una validación cruzada integrada de los bosques aleatorios. Simplemente toma cada observación utilizada en diferentes árboles y encuentra la mejor puntuación.
   
 - <b>n_jobs</b>: En un entorno multiprocesador, si se establece en '-1' significa que no hay restricciones en los núcleos de la CPU que puede usar el modelo. Si se establece en '1', por ejemplo, solo puede usar 1.

In [164]:
rf = RandomForestRegressor(n_estimators= 100, random_state = 10, oob_score=True,
                           max_depth=7, min_samples_leaf=3, min_samples_split=7)


rf.fit(X_train, y_train)
predicted = rf.predict(X_test)
rf_predictions = pd.DataFrame({'Actual':y_test,'Predicted':predicted})
rf_score = rf.score(X_test,y_test)
print("predicted score against actual: %f" % rf_score)
rf_predictions.head()

predicted score against actual: 0.430498

       Actual  Predicted
10987       1   0.261820
11878       1   0.072565
11127       1   0.129916
2486        0   0.255200
392         0   0.000000

#### Búsqueda de hiperparámetros:

In [165]:
params ={'max_depth':range(9,13),
         'min_samples_leaf':range(1,3),
         'min_samples_split':range(2,10,2)
}
grid_search = GridSearchCV(rf,param_grid=params,cv=10)
grid_search.fit(X_train, y_train)


print('Best score: {}'.format(grid_search.best_score_))
print('Best parameters: {}'.format(grid_search.best_params_))

predicted = grid_search.predict(X_test)

grid_predictions = pd.DataFrame({'Actual':y_test,'Predicted':predicted})
score = grid_search.score(X_test,y_test)
print("predicted score against actual: %f" % score)
grid_predictions.head()

Best score: 0.4793768186186881
Best parameters: {'max_depth': 9, 'min_samples_leaf': 2, 'min_samples_split': 6}
predicted score against actual: 0.429479

       Actual  Predicted
10987       1   0.196162
11878       1   0.065952
11127       1   0.098744
2486        0   0.215885
392         0   0.000000

De lo anterior podemos ver que el bosque aleatorio supera al árbol de decisión en un grado considerable. Al utilizar la búsqueda de cuadrícula, es posible que deba jugar con algunos parámetros y cambiar el modelo original como mejor le parezca. La razón es que si ejecuta gridsearch con una cuadrícula de parámetros grande, más tiempo tardará en ejecutarse, por lo que generalmente encuentro beneficioso comenzar con un rango grande con pasos grandes y reducirlo después de cada ejecución a un rango más pequeño con pasos más pequeños. . No he demostrado esto arriba porque ocuparía mucho espacio.

## Support Vector Regressor

La Support Vector Regressor admite regresión lineal y no lineal. Su misión es encajar tantas observaciones tanto como sea posible entre líneas intentando no caer en los márgenes.

Lo que se pretende con el SVM en regresión es buscar el hiperplano que mejor se ajuste a los datos y permita una tolerancia a los errores. En otras palabras, es una regresión lineal con restricciones.

### Parámetros clave:

- kernel: es el parámetro SVR más importante. Los kernels son funciones que transforman los datos en un espacio de mayor dimensión para facilitar la separación no lineal. Puede ser SVR lineal, polinomial o gaussiano.
    - Si tenemos una relación no lineal, podemos seleccionar polinomial o gaussiano (RBF es un tipo gaussiano).
- épsilon: representa al concepto de infracción o penalización que se aplica para las observaciones que caen fuera de los límites.

In [166]:
svm = make_pipeline(StandardScaler(), SVR(kernel="rbf", C=100, gamma=0.1, epsilon=0.1))
svm.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svr', SVR(C=100, gamma=0.1))])

In [167]:
predicted = svm.predict(X_test)

svm_predictions = pd.DataFrame({'Actual':y_test,'Predicted':predicted})

svm_predictions[:5]

################################
#Model score 
################################

# Train dataset

accuracy_train = svm.score(X_train, y_train)
print('Score en conjunto de  train : ', accuracy_train)

# Test dataset
score = svm.score(X_test,y_test)
mseFull = np.mean((y_test - predicted)**2)

print("Score en conjunto de test: %f" % score)
print("Mean Squared Error: %f" % mseFull)

Score en conjunto de  train :  0.8467277265325037
Score en conjunto de test: -0.076452
Mean Squared Error: 0.139408